/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'earningsAmount' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'likes' : IDL.Nat,
  'workCategory' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Story],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getStoriesByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'earningsAmount' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'likes' : IDL.Nat,
    'workCategory' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Story],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getStoriesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Nat], [IDL.Opt(Story)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };